<?php
/**
 * Created by Q-Solutions Studio
 * Date: 09.07.2020
 *
 * @category    Magespices
 * @package     Magespices_GTMDataLayers
 * @author      Maciej Buchert <maciej@qsolutionsstudio.com>
 */
?>
<?php /** @var \Magespices\GTMDataLayers\Block\GTM\Body $block */ ?>

<!-- Google Tag Manager (noscript) -->
<noscript>
    <iframe src="<?= sprintf('https://www.googletagmanager.com/ns.html?id=%s', $block->getGTMIdentifier()) ?>"
            height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
